-- This module is the root of the Smooth4DimensionalPoincareConjectureCanonicalLaneLean Lean proof package.
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.Basic
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.SourcePackage
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.SourceDependencies
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.Formalization
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.ReviewerBridge
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.TheoremStatement
import Smooth4DimensionalPoincareConjectureCanonicalLaneLean.MathlibStatement
